POST http://localhost:3001/api/user
Content-Type: application/json

{
    "username":"alexuser",
    "password":"alexpass"
}

###
POST http://localhost:3001/api/user
Content-Type: application/json

{
    "username":"alexuser2",
    "password":"alexpass2"
}