PUT http://localhost:3001/api/task/63616eeaba6d96395500f49e
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZXh1c2VyIiwiaWQiOiI2MzYwYWJkNDkwY2VlZGJlZjkxYTA2YjIiLCJpYXQiOjE2NjczMzIzNjIsImV4cCI6MTY2NzQxODc2Mn0.-WA8G15ANt1bjKWcNcG8vTDl6yRotN3ykVobAcPjCfM

{
    "text": "Mi primera tarea 2",
    "complete": true
}